---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhsm-conf
data:
  rhsm.conf: |
    {{ BASE64_ENCODED_RHSM_CONF | b64decode | indent(4, indentfirst=False) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: katello-server-ca-pem
data:
  katello-server-ca.pem: |
    {{ BASE64_ENCODED_KATELLO_SERVER_CA | b64decode | indent(4, indentfirst=False) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redhat-repos-conf
data:
  redhat.repo: |
    {{ BASE64_ENCODED_REDHAT_REPO_CONF | b64decode | indent(4, indentfirst=False) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "etc-pki-entitlement"
type: Opaque
data:
{% for entitlement in entitlement_certificates %}
  "{{ entitlement }}.pem": "{{ BASE64_ENCODED_PEM_FILE[entitlement] }}"
  "{{ entitlement }}-key.pem": "{{ BASE64_ENCODED_PEM_FILE_KEY[entitlement] }}"
{% endfor %}
