---
- name: Create secrets and configmaps
  connection: local
  ansible.builtin.template:
    src: secrets_configmaps.yaml
    dest: /tmp/secrets_configmaps.yaml
    mode: "0640"
  delegate_to: localhost
