---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhsm-conf
data:
  rhsm.conf: |
    {{ base64_encoded_rhsm_conf | b64decode | indent(4, first=False) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: katello-server-ca-pem
data:
  katello-server-ca.pem: |
    {{ base64_encoded_katello_server_ca | b64decode | indent(4, first=False) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redhat-repos-conf
data:
  redhat.repo: |
    {{ base64_encoded_redhat_repo_conf | b64decode | indent(4, first=False) }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "etc-pki-entitlement"
type: Opaque
data:
{% for entitlement in entitlement_certificates %}
  "{{ entitlement }}.pem": "{{ base64_encoded_pem_file[entitlement] }}"
  "{{ entitlement }}-key.pem": "{{ base64_encoded_pem_file_key[entitlement] }}"
{% endfor %}
