---
- name: "set facts"
  set_fact:
    standalone_xml: "/etc/opt/rh/rh-sso7/keycloak/standalone/standalone.xml"
    sso_base_url: "https://{{ ansible_fqdn }}/auth"
  tags: always

- name: "Install rh-sso7 group"
  become: true
  dnf:
    name: '@rh-sso7'
    state: present
  tags: always

- name: "allow proxied access in standalone.xml"
  become: true
  lineinfile:
    path: "{{ standalone_xml }}"
    insertafter: '<server name="default-server">'
    regexp: '^(.*<http-listener name="default" socket-binding="http") (redirect-socket="https" enable-http2="true")(.*)'
    line: \1 proxy-address-forwarding="true" redirect-socket="proxy-https" \3
    state: present
    backrefs: true
  tags: always

- name: "add socket-binding in standalone.xml"
  become: true
  lineinfile:
    path: "{{ standalone_xml }}"
    insertafter: '<socket-binding name="txn-status-manager" port="4713"/>'
    line: '        <socket-binding name="proxy-https" port="443"/>'
    regexp: '<socket-binding name="proxy-https" port="443"/>'
    state: present
  tags: always
