---
- name: Fetch Subscription-manager config from source-host
  slurp:
    src: /etc/rhsm/rhsm.conf
  register: BASE64_ENCODED_RHSM_CONF
  delegate_to: "{{ subscription_host }}"

- name: Fetch Subscription-manager server CA
  slurp:
    src: /etc/rhsm/ca/katello-server-ca.pem
  register: BASE64_ENCODED_KATELLO_SERVER_CA
  delegate_to: "{{ subscription_host }}"

- name: Find entitlements
  find:
    path: /etc/pki/entitlement/
    patterns: '^[0-9]*.pem'
    use_regex: true
    file_type: file
  register: entitlement_certificates_find
  delegate_to: "{{ subscription_host }}"

- name: Build filename array
  set_fact:
    entitlement_certificates: "{{ entitlement_certificates_find.files | map(attribute='path') | map('basename') | map('splitext') | map('first') | list }}"

- name: Fetch Subscription-certificates from source-host
  slurp:
    src: "/etc/pki/entitlement/{{ item }}.pem"
  register: BASE64_ENCODED_PEM_FILE_RES
  with_items: "{{ entitlement_certificates }}"
  delegate_to: "{{ subscription_host }}"

- name: Fetch Subscription-certificate key from source-host
  slurp:
    src: "/etc/pki/entitlement/{{ item }}-key.pem"
  register: BASE64_ENCODED_PEM_FILE_KEY_RES
  with_items: "{{ entitlement_certificates }}"
  delegate_to: "{{ subscription_host }}"

- set_fact:
    BASE64_ENCODED_RHSM_CONF: "{{ BASE64_ENCODED_RHSM_CONF.content }}"

- set_fact:
    BASE64_ENCODED_KATELLO_SERVER_CA: "{{ BASE64_ENCODED_KATELLO_SERVER_CA.content }}"

- set_fact:
    BASE64_ENCODED_PEM_FILE: "{{ BASE64_ENCODED_PEM_FILE_RES.results | items2dict(key_name='item', value_name='content') }}"

- set_fact:
    BASE64_ENCODED_PEM_FILE_KEY: "{{ BASE64_ENCODED_PEM_FILE_KEY_RES.results | items2dict(key_name='item', value_name='content') }}"
